class Solution {
    public:
        int orangesRotting(vector<vector<int>>& grid) {

                int n = grid.size();
                        int m = grid[0].size();

                                queue<pair<int, int>> q;
                                        int fresh = 0;

                                                // Put all rotten oranges in queue
                                                        // Count fresh oranges
                                                                for (int i = 0; i < n; i++) {
                                                                            for (int j = 0; j < m; j++) {

                                                                                            if (grid[i][j] == 2) {
                                                                                                                q.push({i, j});
                                                                                                                                }
                                                                                                                                                else if (grid[i][j] == 1) {
                                                                                                                                                                    fresh++;
                                                                                                                                                                                    }
                                                                                                                                                                                                }
                                                                                                                                                                                                        }

                                                                                                                                                                                                                int minutes = 0;

                                                                                                                                                                                                                        int dr[] = {-1, 1, 0, 0};
                                                                                                                                                                                                                                int dc[] = {0, 0, -1, 1};

                                                                                                                                                                                                                                        // BFS
                                                                                                                                                                                                                                                while (!q.empty() && fresh > 0) {

                                                                                                                                                                                                                                                            int size = q.size();

                                                                                                                                                                                                                                                                        // Process all oranges rotten at this minute
                                                                                                                                                                                                                                                                                    for (int i = 0; i < size; i++) {

                                                                                                                                                                                                                                                                                                    auto [r, c] = q.front();
                                                                                                                                                                                                                                                                                                                    q.pop();

                                                                                                                                                                                                                                                                                                                                    for (int d = 0; d < 4; d++) {

                                                                                                                                                                                                                                                                                                                                                        int nr = r + dr[d];
                                                                                                                                                                                                                                                                                                                                                                            int nc = c + dc[d];

                                                                                                                                                                                                                                                                                                                                                                                                if (nr >= 0 && nr < n &&
                                                                                                                                                                                                                                                                                                                                                                                                                        nc >= 0 && nc < m &&
                                                                                                                                                                                                                                                                                                                                                                                                                                                grid[nr][nc] == 1) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        grid[nr][nc] = 2;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                fresh--;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        q.push({nr, nc});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    minutes++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // If fresh oranges remain, impossible
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return fresh == 0 ? minutes : -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };