
class Solution {
public:
    int minimumPairRemoval(vector<int>& nums) {
            int n = nums.size();

                    vector<long long> a(nums.begin(), nums.end());
                            vector<int> prev(n), nxt(n);
                                    vector<bool> alive(n, true);

                                            for (int i = 0; i < n; i++) {
                                                        prev[i] = i - 1;
                                                                    nxt[i] = i + 1;
                                                                            }
                                                                                    nxt[n - 1] = -1;

                                                                                            // {pair sum, left index, right index}
                                                                                                    using T = tuple<long long, int, int>;
                                                                                                            priority_queue<T, vector<T>, greater<T>> pq;

                                                                                                                    for (int i = 0; i < n - 1; i++) {
                                                                                                                                pq.push({a[i] + a[i + 1], i, i + 1});
                                                                                                                                        }

                                                                                                                                                // Count adjacent inversions
                                                                                                                                                        int bad = 0;
                                                                                                                                                                for (int i = 0; i < n - 1; i++) {
                                                                                                                                                                            if (a[i] > a[i + 1]) {
                                                                                                                                                                                            bad++;
                                                                                                                                                                                                        }
                                                                                                                                                                                                                }

                                                                                                                                                                                                                        int operations = 0;

                                                                                                                                                                                                                                auto removeBad = [&](int x, int y) {
                                                                                                                                                                                                                                            if (x != -1 && y != -1 && a[x] > a[y])
                                                                                                                                                                                                                                                            bad--;
                                                                                                                                                                                                                                                                    };

                                                                                                                                                                                                                                                                            auto addBad = [&](int x, int y) {
                                                                                                                                                                                                                                                                                        if (x != -1 && y != -1 && a[x] > a[y])
                                                                                                                                                                                                                                                                                                        bad++;
                                                                                                                                                                                                                                                                                                                };

                                                                                                                                                                                                                                                                                                                        while (bad > 0) {
                                                                                                                                                                                                                                                                                                                                    auto [sum, l, r] = pq.top();
                                                                                                                                                                                                                                                                                                                                                pq.pop();

                                                                                                                                                                                                                                                                                                                                                            // Ignore outdated heap entries
                                                                                                                                                                                                                                                                                                                                                                        if (!alive[l] || !alive[r] || nxt[l] != r ||
                                                                                                                                                                                                                                                                                                                                                                                        a[l] + a[r] != sum) {
                                                                                                                                                                                                                                                                                                                                                                                                        continue;
                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                int p = prev[l];
                                                                                                                                                                                                                                                                                                                                                                                                                                            int q = nxt[r];

                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Remove old adjacent inversion contributions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    removeBad(p, l);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                removeBad(l, r);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            removeBad(r, q);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Merge r into l
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    a[l] += a[r];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                alive[r] = false;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            nxt[l] = q;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (q != -1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        prev[q] = l;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Add new adjacent inversion contributions
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                addBad(p, l);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            addBad(l, q);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        operations++;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Insert updated adjacent pairs
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (p != -1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                pq.push({a[p] + a[l], p, l});

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (q != -1)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            pq.push({a[l] + a[q], l, q});
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return operations;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                };                                                                                                                                                                                                                                                                                                                                                                                                        