class Solution {
    public:

        struct TrieNode {
                TrieNode* child[26];
                        string word;

                                TrieNode() {
                                            for (int i = 0; i < 26; i++)
                                                            child[i] = NULL;

                                                                        word = "";
                                                                                }
                                                                                    };

                                                                                        TrieNode* root = new TrieNode();

                                                                                            vector<string> ans;

                                                                                                int m, n;

                                                                                                    void insert(string word) {
                                                                                                            TrieNode* curr = root;

                                                                                                                    for (char c : word) {
                                                                                                                                int index = c - 'a';

                                                                                                                                            if (curr->child[index] == NULL)
                                                                                                                                                            curr->child[index] = new TrieNode();

                                                                                                                                                                        curr = curr->child[index];
                                                                                                                                                                                }

                                                                                                                                                                                        curr->word = word;
                                                                                                                                                                                            }

                                                                                                                                                                                                void dfs(vector<vector<char>>& board, int i, int j, TrieNode* node) {

                                                                                                                                                                                                        // Boundary check
                                                                                                                                                                                                                if (i < 0 || i >= m || j < 0 || j >= n)
                                                                                                                                                                                                                            return;

                                                                                                                                                                                                                                    // Already visited
                                                                                                                                                                                                                                            if (board[i][j] == '#')
                                                                                                                                                                                                                                                        return;

                                                                                                                                                                                                                                                                char c = board[i][j];

                                                                                                                                                                                                                                                                        int index = c - 'a';

                                                                                                                                                                                                                                                                                // Character not present in Trie
                                                                                                                                                                                                                                                                                        if (node->child[index] == NULL)
                                                                                                                                                                                                                                                                                                    return;

                                                                                                                                                                                                                                                                                                            node = node->child[index];

                                                                                                                                                                                                                                                                                                                    // Found a complete word
                                                                                                                                                                                                                                                                                                                            if (node->word != "") {
                                                                                                                                                                                                                                                                                                                                        ans.push_back(node->word);

                                                                                                                                                                                                                                                                                                                                                    // Avoid duplicate answer
                                                                                                                                                                                                                                                                                                                                                                node->word = "";
                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                // Mark visited
                                                                                                                                                                                                                                                                                                                                                                                        board[i][j] = '#';

                                                                                                                                                                                                                                                                                                                                                                                                // Up
                                                                                                                                                                                                                                                                                                                                                                                                        dfs(board, i - 1, j, node);

                                                                                                                                                                                                                                                                                                                                                                                                                // Down
                                                                                                                                                                                                                                                                                                                                                                                                                        dfs(board, i + 1, j, node);

                                                                                                                                                                                                                                                                                                                                                                                                                                // Left
                                                                                                                                                                                                                                                                                                                                                                                                                                        dfs(board, i, j - 1, node);

                                                                                                                                                                                                                                                                                                                                                                                                                                                // Right
                                                                                                                                                                                                                                                                                                                                                                                                                                                        dfs(board, i, j + 1, node);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Backtrack
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        board[i][j] = c;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                vector<string> findWords(vector<vector<char>>& board,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             vector<string>& words) {

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     m = board.size();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             n = board[0].size();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     // Build Trie
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                             for (string word : words)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         insert(word);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 // Start DFS from every cell
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         for (int i = 0; i < m; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     for (int j = 0; j < n; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     dfs(board, i, j, root);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                 return ans;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     };